### ISSUE TITLE
How complete is this library?

### ISSUE THREAD

**Issue by stwiname** [danderson/nat#10]
I cant find any reference to TURN and don't seem to have any luck across multiple networks

**Comment by danderson** [comment]
This library does not implement TURN, it only implements a variant of the ICE protocol for direct connection establishment between two peers. It should be the state of the art for p2p NAT busting, but it can still fail in a variety of scenarios where the NATs are too complex to break through.

In those cases, a robust application has to fall back to third-party relaying, but this library doesn't implement that.
